/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafegui;

/**
 *
 * @author Chandra
 */
public class MENU_CAFE extends javax.swing.JFrame {

    /**
     * Creates new form MENU_CAFE
     */
    public MENU_CAFE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMenu = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTerpilih = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtBanyak = new javax.swing.JTextField();
        jmlHarga = new javax.swing.JTextField();
        tHarga = new javax.swing.JTextField();
        jmlBayar = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU CAFE GUI ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        listMenu.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        listMenu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Ayam Bakar", "2. Ayam Penyet", "3. Soto Ayam", "4. Mie Ayam", "5. Nasi Goreng", "6. Seblak Ceker", "7. Bakso", "8. Ayam Goreng", "9. Pecel Lele", "10. Pecel Ayam", "11. Air Mineral", "12. Es Teh Manis", "13. Es Jeruk", "14. Es Buah", "15. Pop Ice" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listMenu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listMenuValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listMenu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 102, 202, 317));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu Terpilih : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Harga");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Banyaknya");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 178, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jumlah Harga");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 234, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("TOTAL HARGA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jumlah Bayar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Kembalian");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 386, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel9.setText("Pilihan Menu :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 68, -1, -1));
        getContentPane().add(txtTerpilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 102, 217, -1));
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 150, 217, -1));
        getContentPane().add(txtBanyak, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 200, 217, -1));
        getContentPane().add(jmlHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 251, 217, -1));
        getContentPane().add(tHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 297, 217, -1));
        getContentPane().add(jmlBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 357, 217, -1));
        getContentPane().add(txtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 408, 217, -1));

        btn1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn1.setText("Hitung");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 251, -1, -1));

        btn2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn2.setText("Hitung");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 357, -1, -1));

        btn3.setText("Reset");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 408, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton2.setText("Keluar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 70, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/cape.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listMenuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listMenuValueChanged
        String menu;
        menu = (String)listMenu.getSelectedValue();
        txtTerpilih.setText(menu);
        switch(menu){
            case "1. Ayam Bakar": txtHarga.setText("20000");
            break;
            case "2. Ayam Penyet": txtHarga.setText("25000");
            break;
            case "3. Soto Ayam": txtHarga.setText("10000");
            break;
            case "4. Mie Ayam": txtHarga.setText("10000");
            break;
            case "5. Nasi Goreng": txtHarga.setText("15000");
            break;
            case "6. Seblak Ceker": txtHarga.setText("12000");
            break;
            case "7. Bakso": txtHarga.setText("10000");
            break;
            case "8. Ayam Goreng": txtHarga.setText("15000");
            break;
            case "9. Pecel Lele": txtHarga.setText("15000");
            break;
            case "10. Pecel Ayam": txtHarga.setText("13000");
            break;
            case "11. Air Mineral": txtHarga.setText("5000");
            break;
            case "12. Es Teh Manis": txtHarga.setText("5000");
            break;
            case "13. Es Jeruk": txtHarga.setText("6000");
            break;
            case "14. Es Buah": txtHarga.setText("7000");
            break;
            case "15. Pop Ice": txtHarga.setText("3000");
            break;
            /*
            case "1": txtHarga.setText("20000");
            break;
            case "2": txtHarga.setText("25000");
            break;
            case "3": txtHarga.setText("10000");
            break;
            case "4": txtHarga.setText("10000");
            break;
            case "5": txtHarga.setText("15000");
            break;
            case "6": txtHarga.setText("12000");
            break;
            case "7": txtHarga.setText("10000");
            break;
            case "8": txtHarga.setText("15000");
            break;
            case "9": txtHarga.setText("15000");
            break;
            case "10": txtHarga.setText("13000");
            break;
            case "11": txtHarga.setText("5000");
            break;
            case "12": txtHarga.setText("5000");
            break;
            case "13": txtHarga.setText("6000");
            break;
            case "14": txtHarga.setText("7000");
            break;
            case "15": txtHarga.setText("3000");
            break;
            */
        }
        
    }//GEN-LAST:event_listMenuValueChanged
    int harga, banyak, jml_harga, total_harga;
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
      harga=Integer.parseInt(txtHarga.getText());
        banyak=Integer.parseInt(txtBanyak.getText());
        
       jml_harga=harga*banyak;
       jmlHarga.setText(Integer.toString(jml_harga));
       tHarga.setText(Integer.toString(jml_harga));
     
       total_harga=Integer.parseInt(tHarga.getText());
       total_harga=jml_harga + total_harga;
       //tHarga.setText(Integer.toString(total_harga));
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
     int bayar,kembalian;
        bayar=Integer.parseInt(jmlBayar.getText());
        total_harga=Integer.parseInt(tHarga.getText());
        kembalian=bayar-total_harga;
        txtKembalian.setText(Integer.toString(kembalian));
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txtTerpilih.setText("");
        txtHarga.setText("0");
        txtBanyak.setText("0");
        jmlHarga.setText("0");
        tHarga.setText("0");
        jmlBayar.setText("0");
        txtKembalian.setText("0");
    }//GEN-LAST:event_btn3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU_CAFE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU_CAFE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU_CAFE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU_CAFE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU_CAFE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlBayar;
    private javax.swing.JTextField jmlHarga;
    private javax.swing.JList<String> listMenu;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField txtBanyak;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtTerpilih;
    // End of variables declaration//GEN-END:variables
}
