/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe;

import static java.time.InstantSource.system;
import javax.swing.JOptionPane;

/**
 *
 * @author yosef
 */
public class cafee extends javax.swing.JFrame {

    private Object SpBanyaknya;

    /**
     * Creates new form cafee
     */
    public cafee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJmlHarga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTotalHarga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListMenu = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        txtJmlBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        txtTerpilih = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTerpilih1 = new javax.swing.JTextField();
        spBanyaknya = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtJmlHarga.setEditable(false);
        txtJmlHarga.setText("0");
        txtJmlHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlHargaActionPerformed(evt);
            }
        });
        getContentPane().add(txtJmlHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 246, 251, -1));

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 196, -1, -1));

        jLabel6.setFont(new java.awt.Font("Britannic Bold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jumlah Harga :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 224, 89, -1));

        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NYATU' CAF'E");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 107, 28));

        txtTotalHarga.setEditable(false);
        txtTotalHarga.setBackground(new java.awt.Color(255, 0, 0));
        txtTotalHarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTotalHarga.setText("0");
        txtTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHargaActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 300, 251, -1));

        jLabel8.setFont(new java.awt.Font("Britannic Bold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah Bayar :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 328, 85, -1));

        ListMenu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "KENBRUT", "CHIKBRUT", "BEGOBRUT", "BUMI", "BURGER SLICE BEEF", "ICE CREAM", "ES BOBRUT", "ES CAPUCINO BOBRUT", "CAPCIN", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListMenu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ListMenuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                ListMenuAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ListMenu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListMenuValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListMenu);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 61, 155, 173));

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 400, -1, -1));

        txtJmlBayar.setText("0");
        txtJmlBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlBayarActionPerformed(evt);
            }
        });
        getContentPane().add(txtJmlBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 350, 251, -1));

        jLabel9.setFont(new java.awt.Font("Britannic Bold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kembalian :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 376, 77, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pilihan Menu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 156, 21));

        jLabel4.setFont(new java.awt.Font("Britannic Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 111, -1, -1));

        txtKembalian.setEditable(false);
        txtKembalian.setText("0");
        txtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembalianActionPerformed(evt);
            }
        });
        getContentPane().add(txtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 400, 251, -1));

        txtTerpilih.setBackground(new java.awt.Color(255, 0, 51));
        txtTerpilih.setFont(new java.awt.Font("Britannic Bold", 0, 12)); // NOI18N
        txtTerpilih.setForeground(new java.awt.Color(255, 255, 255));
        txtTerpilih.setText("Menu Terpilih :");
        getContentPane().add(txtTerpilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 55, 132, -1));

        txtHarga.setEditable(false);
        txtHarga.setText("0");
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 133, 251, -1));

        jLabel5.setFont(new java.awt.Font("Britannic Bold", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Banyaknya :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 71, -1));

        jLabel10.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL HARGA :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 280, -1, 14));

        txtTerpilih1.setEditable(false);
        txtTerpilih1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerpilih1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtTerpilih1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 77, 251, -1));
        getContentPane().add(spBanyaknya, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 251, 20));

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 429, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafe/danu lagi danu lagi.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 530, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int harga, banyak, jml_hrg, total_hrg;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        harga = Integer.parseInt(txtHarga.getText());
        banyak = (Integer) spBanyaknya.getValue();

        jml_hrg = harga * banyak;
        txtJmlHarga.setText(Integer.toString(jml_hrg));

        total_hrg = Integer.parseInt(txtTotalHarga.getText());
        total_hrg = jml_hrg + total_hrg;
        txtTotalHarga.setText(Integer.toString(total_hrg));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int bayar, kembalian;
        bayar = Integer.parseInt(txtJmlBayar.getText());
        total_hrg = Integer.parseInt(txtTotalHarga.getText());
        kembalian = bayar - total_hrg;
        txtKembalian.setText(Integer.toString(kembalian));
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHargaActionPerformed

    private void ListMenuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListMenuValueChanged
        String menu;
        menu = (String) ListMenu.getSelectedValue();
        txtTerpilih1.setText(menu);
        switch (menu) {
            case "KENBRUT":
                txtHarga.setText("25000");
                break;
            case "CHIKBRUT":
                txtHarga.setText("15000");
                break;
            case "BEGOBRUT":
                txtHarga.setText("35000");
                break;
            case "BUMI":
                txtHarga.setText("5000");
                break;
            case "BURGER SLICE BEEF":
                txtHarga.setText("35000");
                break;
            case "ICE CREAM":
                txtHarga.setText("8000");
                break;
            case "ES BOBRUT":
                txtHarga.setText("20000");
                break;
            case "ES CAPUCINO BOBRUT":
                txtHarga.setText("27000");
                break;
            case "CAPCIN":
                txtHarga.setText("10000");
                break;
        }
    }//GEN-LAST:event_ListMenuValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtTerpilih.setText("");
        txtHarga.setText("0");
        spBanyaknya.setValue (0);
        txtJmlHarga.setText("0");
        txtTotalHarga.setText("0");
        txtJmlBayar.setText("0");
        txtKembalian.setText("0");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtJmlBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlBayarActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianActionPerformed

    private void txtJmlHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlHargaActionPerformed

    private void ListMenuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ListMenuAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ListMenuAncestorAdded

    private void ListMenuAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ListMenuAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_ListMenuAncestorMoved

    private void txtTerpilih1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerpilih1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerpilih1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    if(JOptionPane.showConfirmDialog(null, "UDAH MAU KELUAR ?", "yakin?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
        System.exit(0);
    }
    }
       
    {
        
        
        
        
               
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cafee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cafee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cafee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cafee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cafee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spBanyaknya;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJmlBayar;
    private javax.swing.JTextField txtJmlHarga;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JLabel txtTerpilih;
    private javax.swing.JTextField txtTerpilih1;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
